[build]
builder = "NIXPACKS"

[[services]]
name = "securechat-frontend"
rootDirectory = "."
buildCommand = "npm install && npm run build"
startCommand = "npx serve -s dist -l $PORT"
watchPatterns = ["src/**", "public/**"]

[[services]]
name = "securechat-backend"
rootDirectory = "server"
buildCommand = "npm install"
startCommand = "npm start"
watchPatterns = ["server/**/*.js"]

