services:
  # Backend API Service
  - type: web
    name: securechat-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        fromDatabase:
          name: securechat-db
          property: connectionString
  
  # Frontend Static Site
  - type: staticSite
    name: securechat-frontend
    buildCommand: npm install && npm run build
    publishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: securechat-backend
          property: host

databases:
  - name: securechat-db
    databaseName: mingleup
    plan: free